---
- name: Install ms sql
  hosts: win
  tasks: 
   - name: Download Ms-Sql
     win_get_url:
      url: 'https://github.com/DwijeshMishra/script.ps1/blob/master/SQL2019-SSEI-Dev.exe?raw=true'
      dest: 'C:\Windows\Temp\SQL2019-SSEI-Dev.exe'

   - name: Run Ms_Sql exe
     raw: 'C:\Windows\Temp\SQL2019-SSEI-Dev.exe /SILENT /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"'   
